/** @format */

export default {
  login: "LotusAndMe",
  id: 60803449,
  node_id: "MDQ6VXNlcjYwODAzNDQ5",
  avatar_url: "https://avatars.githubusercontent.com/u/60803449?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/LotusAndMe",
  html_url: "https://github.com/LotusAndMe",
  followers_url: "https://api.github.com/users/LotusAndMe/followers",
  following_url:
    "https://api.github.com/users/LotusAndMe/following{/other_user}",
  gists_url: "https://api.github.com/users/LotusAndMe/gists{/gist_id}",
  starred_url: "https://api.github.com/users/LotusAndMe/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/LotusAndMe/subscriptions",
  organizations_url: "https://api.github.com/users/LotusAndMe/orgs",
  repos_url: "https://api.github.com/users/LotusAndMe/repos",
  events_url: "https://api.github.com/users/LotusAndMe/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/LotusAndMe/received_events",
  type: "User",
  site_admin: false,
  name: "andriiokhrimenko.github.io",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 3,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-02-08T02:48:50Z",
  updated_at: "2022-05-16T20:36:21Z",
};
